#!/bin/sh
# simple script which will configure my home environment

ETCDIR=$CWD
BASEDIR=`cd ..; echo $PWD`
SRCDIR=`cd ../..; echo $PWD`
echo $BASEDIR

# emacs config
echo configuring emacs-lisp
rm -f $HOME/emacs-lisp
ln -s $BASEDIR/emacs-lisp $HOME/emacs-lisp

echo configuring .emacs
rm -f $HOME/.emacs
ln -s $BASEDIR/emacs/.emacs $HOME/.emacs

echo configuring .emacs.d
rm -rf $HOME/.emacs.d
ln -s $BASEDIR/emacs/.emacs.d $HOME/.emacs.d

# bash
echo configuring bash
rm -f $HOME/.profile
ln -s $BASEDIR/bash/.profile $HOME/.profile

rm -f $HOME/.bashrc
ln -s $BASEDIR/bash/.bashrc $HOME/.bashrc

# etc
echo configuring etc
rm -f $HOME/etc
ln -s $BASEDIR/etc $HOME/etc
